import type { EnemyConfig } from '../types';

export const ENEMY_CONFIGS: EnemyConfig[] = [
  {
    id: 'common-melee',
    name: 'Common Melee',
    speed: 80,
    health: 200,
    damage: 5,
    attackRange: 50,
    detectionRange: 350,
    type: 'melee',
    originX: 0.5,
    originY: 0.8,
    scale: 1.5,
    hitboxWidth: 30,
    hitboxHeight: 35,
    anims: {
      idle:   { frameCount: 4,  frameRate: 8,  repeat: -1 },
      walk:   { frameCount: 5,  frameRate: 10, repeat: -1 },
      attack: { frameCount: 8,  frameRate: 12, repeat: 0  },
      death:  { frameCount: 12, frameRate: 10, repeat: 0  },
    },
  },
  {
    id: 'elite-flame',
    name: 'Elite Flame',
    speed: 90,
    health: 300,
    damage: 8,
    attackRange: 55,
    detectionRange: 380,
    type: 'melee',
    originX: 0.5,
    originY: 0.8,
    scale: 1.5,
    hitboxWidth: 30,
    hitboxHeight: 35,
    anims: {
      idle:   { frameCount: 4,  frameRate: 8,  repeat: -1 },
      walk:   { frameCount: 5,  frameRate: 10, repeat: -1 },
      attack: { frameCount: 26, frameRate: 18, repeat: 0  },
      death:  { frameCount: 17, frameRate: 10, repeat: 0  },
    },
  },
  {
    id: 'drone-pod',
    name: 'Drone Pod',
    speed: 70,
    health: 250,
    damage: 6,
    attackRange: 200,
    detectionRange: 400,
    type: 'ranged',
    bulletKey: 'pod_laser_bullet',
    originX: 0.5,
    originY: 0.5,
    scale: 1.5,
    hitboxWidth: 35,
    hitboxHeight: 30,
    anims: {
      idle:   { frameCount: 8,  frameRate: 8,  repeat: -1 },
      walk:   { frameCount: 8,  frameRate: 10, repeat: -1, folder: 'movement', filePrefix: 'drone_pod_movement' },
      attack: { frameCount: 16, frameRate: 14, repeat: 0  },
      death:  { frameCount: 14, frameRate: 10, repeat: 0  },
    },
  },
  {
    id: 'hen-mini-drone',
    name: 'Hen Mini Drone',
    speed: 100,
    health: 150,
    damage: 4,
    attackRange: 60,
    detectionRange: 600,
    type: 'melee',
    originX: 0.5,
    originY: 0.5,
    scale: 1.5,
    hitboxWidth: 25,
    hitboxHeight: 25,
    hoverOffsetY: -50,
    anims: {
      idle:   { frameCount: 4,  frameRate: 8,  repeat: -1 },
      attack: { frameCount: 8,  frameRate: 12, repeat: 0  },
      death:  { frameCount: 12, frameRate: 10, repeat: 0  },
    },
  },
  {
    id: 'special-walker',
    name: 'Special Walker',
    speed: 75,
    health: 350,
    damage: 7,
    attackRange: 180,
    detectionRange: 400,
    type: 'ranged',
    bulletKey: 'special_laser_bullet',
    originX: 0.5,
    originY: 0.8,
    scale: 1.5,
    hitboxWidth: 30,
    hitboxHeight: 40,
    anims: {
      idle:      { frameCount: 3,  frameRate: 6,  repeat: -1 },
      walk:      { frameCount: 6,  frameRate: 10, repeat: -1 },
      'attack-a': { frameCount: 18, frameRate: 14, repeat: 0  },
      'attack-b': { frameCount: 7,  frameRate: 14, repeat: 0  },
      death:     { frameCount: 16, frameRate: 10, repeat: 0  },
    },
  },
  {
    id: 'boss-hen',
    name: 'Boss Hen',
    speed: 65,
    health: 1200,
    damage: 10,
    attackRange: 220,
    detectionRange: 500,
    type: 'boss',
    bulletKey: 'hen_laser_bullet',
    bulletScale: 0.5,
    bulletOriginNormY: 0.62,
    originX: 0.5,
    originY: 0.8,
    scale: 1.5,
    hitboxWidth: 45,
    hitboxHeight: 50,
    healthBarOffsetY: 45,
    anims: {
      idle:      { frameCount: 4,  frameRate: 6,  repeat: -1 },
      walk:      { frameCount: 8,  frameRate: 10, repeat: -1 },
      'attack-a': { frameCount: 20, frameRate: 14, repeat: 0  },
      'attack-b': { frameCount: 27, frameRate: 14, repeat: 0  },
      'jump-fly': { frameCount: 22, frameRate: 14, repeat: 0  },
      death:     { frameCount: 54, frameRate: 14, repeat: 0  },
    },
    spawnConfig: { enemyId: 'hen-mini-drone', frames: [13, 18, 23] },
  },
];
