import type { HeroConfig } from '../types';

export const HERO_CONFIGS: HeroConfig[] = [
  {
    id: 1,
    name: 'Hero 1',
    speed: 220,
    health: 100,
    selectFolder: 'Character Select',
    hasDashDust: true,
    anims: {
      idle:   { frameCount: 4,  frameRate: 8,  repeat: -1, padded: false },
      run:    { frameCount: 5,  frameRate: 10, repeat: -1, padded: false },
      jump:   { frameCount: 10, frameRate: 10, repeat: 0,  padded: false },
      dash:   { frameCount: 12, frameRate: 12, repeat: 0,  padded: false },
      death:  { frameCount: 12, frameRate: 8,  repeat: 0,  padded: false },
      select: { frameCount: 20, frameRate: 10, repeat: -1, padded: false },
    },
  },
  {
    id: 2,
    name: 'Hero 2',
    speed: 220,
    health: 100,
    selectFolder: 'Select',
    hasDashDust: false,
    anims: {
      idle:   { frameCount: 4,  frameRate: 8,  repeat: -1, padded: true },
      run:    { frameCount: 5,  frameRate: 10, repeat: -1, padded: true },
      jump:   { frameCount: 10, frameRate: 10, repeat: 0,  padded: true },
      dash:   { frameCount: 10, frameRate: 12, repeat: 0,  padded: true },
      death:  { frameCount: 12, frameRate: 8,  repeat: 0,  padded: true },
      select: { frameCount: 20, frameRate: 10, repeat: -1, padded: true },
    },
  },
  {
    id: 3,
    name: 'Hero 3',
    speed: 220,
    health: 100,
    selectFolder: 'Select',
    hasDashDust: false,
    anims: {
      idle:   { frameCount: 4,  frameRate: 8,  repeat: -1, padded: true },
      run:    { frameCount: 5,  frameRate: 10, repeat: -1, padded: true },
      jump:   { frameCount: 10, frameRate: 10, repeat: 0,  padded: true },
      dash:   { frameCount: 10, frameRate: 12, repeat: 0,  padded: true },
      death:  { frameCount: 12, frameRate: 8,  repeat: 0,  padded: true },
      select: { frameCount: 20, frameRate: 10, repeat: -1, padded: true },
    },
  },
  {
    id: 4,
    name: 'Hero 4',
    speed: 220,
    health: 100,
    selectFolder: 'Select',
    hasDashDust: true,
    anims: {
      idle:   { frameCount: 4,  frameRate: 8,  repeat: -1, padded: true },
      run:    { frameCount: 5,  frameRate: 10, repeat: -1, padded: true },
      jump:   { frameCount: 11, frameRate: 10, repeat: 0,  padded: true },
      dash:   { frameCount: 12, frameRate: 12, repeat: 0,  padded: true },
      death:  { frameCount: 12, frameRate: 8,  repeat: 0,  padded: true },
      select: { frameCount: 20, frameRate: 10, repeat: -1, padded: true },
    },
  },
  {
    id: 5,
    name: 'Hero 5',
    speed: 220,
    health: 100,
    selectFolder: 'Select',
    hasDashDust: true,
    anims: {
      idle:   { frameCount: 4,  frameRate: 8,  repeat: -1, padded: true },
      run:    { frameCount: 5,  frameRate: 10, repeat: -1, padded: true },
      jump:   { frameCount: 11, frameRate: 10, repeat: 0,  padded: true },
      dash:   { frameCount: 12, frameRate: 12, repeat: 0,  padded: true },
      death:  { frameCount: 12, frameRate: 8,  repeat: 0,  padded: true },
      select: { frameCount: 20, frameRate: 10, repeat: -1, padded: true },
    },
  },
  {
    id: 6,
    name: 'Hero 6',
    speed: 220,
    health: 100,
    selectFolder: 'Select',
    hasDashDust: true,
    anims: {
      idle:   { frameCount: 4,  frameRate: 8,  repeat: -1, padded: true },
      run:    { frameCount: 5,  frameRate: 10, repeat: -1, padded: true },
      jump:   { frameCount: 11, frameRate: 10, repeat: 0,  padded: true },
      dash:   { frameCount: 12, frameRate: 12, repeat: 0,  padded: true },
      death:  { frameCount: 12, frameRate: 8,  repeat: 0,  padded: true },
      select: { frameCount: 20, frameRate: 10, repeat: -1, padded: true },
    },
  },
];
