import type { WeaponConfig } from '../types';

export const WEAPON_CONFIGS: WeaponConfig[] = [
  {
    id: 'laser-beam',
    displayName: 'Laser Beam',
    type: 'ranged',
    frameCount: 3,
    frameRate: 8,
    assetFolder: 'Laser Beam',
    assetFileStem: 'Laser-Beam',
    bulletTextureKey: 'bullet_laser-beam',
    projectileSpeed: 600,
    damage: 25,
  },
  {
    id: 'laser-gun',
    displayName: 'Laser Gun',
    type: 'ranged',
    frameCount: 2,
    frameRate: 8,
    assetFolder: 'Laser Gun',
    assetFileStem: 'Laser-Gun',
    bulletTextureKey: 'bullet_laser-gun',
    projectileSpeed: 500,
    damage: 15,
  },
  {
    // Lightsaber frames use "New lightsaber01.png" naming — handled in PreloadScene
    id: 'lightsaber',
    displayName: 'Lightsaber',
    type: 'melee',
    frameCount: 6,
    frameRate: 12,
    assetFolder: 'Lightsaber',
    assetFileStem: 'New lightsaber',
    swingDurationMs: 400,
    damage: 40,
  },
  {
    id: 'machine-gun',
    displayName: 'Machine Gun',
    type: 'ranged',
    frameCount: 2,
    frameRate: 12,
    assetFolder: 'Machine Gun',
    assetFileStem: 'Machine-Gun',
    bulletTextureKey: 'bullet_machinegun',
    projectileSpeed: 700,
    damage: 10,
  },
  {
    id: 'shotgun',
    displayName: 'Shotgun',
    type: 'ranged',
    frameCount: 3,
    frameRate: 8,
    assetFolder: 'Shotgun',
    assetFileStem: 'Shotgun',
    bulletTextureKey: 'bullet_shotgun',
    projectileSpeed: 450,
    damage: 15,
    projectileCount: 5,
    spreadDeg: 30,
  },
];
