import type { WeaponConfig } from '../types';

export const WEAPON_CONFIGS: WeaponConfig[] = [
  {
    id: 'laser-beam',
    displayName: 'Laser Beam',
    type: 'beam',
    frameCount: 3,
    frameRate: 8,
    bulletFrameKey: 'bullet_laser-beam',
    damage: 25,
    beamDurationMs: 250,
    fireRateMs: 700,
  },
  {
    id: 'laser-gun',
    displayName: 'Laser Gun',
    type: 'ranged',
    frameCount: 2,
    frameRate: 8,
    bulletFrameKey: 'bullet_laser-gun',
    projectileSpeed: 500,
    damage: 15,
    originX: 0.36,
    originY: 0.71,
  },
  {
    id: 'lightsaber',
    displayName: 'Lightsaber',
    type: 'melee',
    frameCount: 6,
    frameRate: 12,
    swingDurationMs: 400,
    damage: 40,
    originX: 0.5,
    originY: 0.44,
    offsetX: 5,
  },
  {
    id: 'machine-gun',
    displayName: 'Machine Gun',
    type: 'ranged',
    frameCount: 2,
    frameRate: 12,
    bulletFrameKey: 'bullet_machinegun',
    projectileSpeed: 700,
    damage: 10,
    fireRateMs: 100,
  },
  {
    id: 'shotgun',
    displayName: 'Shotgun',
    type: 'ranged',
    frameCount: 3,
    frameRate: 8,
    bulletFrameKey: 'bullet_shotgun',
    projectileSpeed: 450,
    damage: 15,
    fireRateMs: 500,
    projectileCount: 3,
    spreadDeg: 10,
    lifespanMs: 600,
    muzzleSmoke: true,
    bulletTrail: true,
    projectileScale: 0.6,
  },
];
