import type { WeaponConfig } from '../types';

export const WEAPON_CONFIGS: WeaponConfig[] = [
  {
    id: 'laser-beam',
    displayName: 'Laser Beam',
    type: 'ranged',
    frameCount: 3,
    frameRate: 8,
    bulletTextureKey: 'bullet_laser-beam',
    projectileSpeed: 600,
    damage: 25,
  },
  {
    id: 'laser-gun',
    displayName: 'Laser Gun',
    type: 'ranged',
    frameCount: 2,
    frameRate: 8,
    bulletTextureKey: 'bullet_laser-gun',
    projectileSpeed: 500,
    damage: 15,
  },
  {
    id: 'lightsaber',
    displayName: 'Lightsaber',
    type: 'melee',
    frameCount: 6,
    frameRate: 12,
    swingDurationMs: 400,
    damage: 40,
  },
  {
    id: 'machine-gun',
    displayName: 'Machine Gun',
    type: 'ranged',
    frameCount: 2,
    frameRate: 12,
    bulletTextureKey: 'bullet_machinegun',
    projectileSpeed: 700,
    damage: 10,
  },
  {
    id: 'shotgun',
    displayName: 'Shotgun',
    type: 'ranged',
    frameCount: 3,
    frameRate: 8,
    bulletTextureKey: 'bullet_shotgun',
    projectileSpeed: 450,
    damage: 15,
    projectileCount: 5,
    spreadDeg: 30,
  },
];
